export{default as carrito} from './carrito.svg'
export{default as user2} from './user2.svg'
export{default as store} from './store.svg'
export{default as shop} from './shop.png'
export {default as cart} from './cart.png'
export{default as cart2} from './cart2.png'
export {default as free_icon_1} from './free_icon_1.svg'
export {default as searchIcon} from './searchIcon.svg'
export {default as filter} from './filter.svg'
export {default as minus} from './minus.svg'
export {default as plus} from './plus.svg'
export {default as github} from './github.svg'
export {default as linkedin} from './linkedin.svg'
export {default as deleteImg} from './deleteImg.svg'
export {default as deleteIcon} from './deleteIcon.svg'
